export const USER_ACTION_TYPES = {
  SET_USER: "user/SET_CURRENT_USER",
  CHECK_USER_SESSION: "user/CHECK_USER_SESSION",
  GOOGLE_SIGNIN_START: "user/GOOGLE_SIGNIN_START",
  EMAIL_SIGNIN_START: "user/EMAIL_SIGNIN_START",
  USER_SIGNIN_SUCCESS: "user/USER_SIGNIN_SUCCESS",
  USER_SIGNIN_FAIL: "user/USER_SIGNIN_FAIL",
  USER_SIGNUP_START: "user/USER_SIGNUP_START",
  USER_SIGNUP_SUCCESS: "user/USER_SIGNUP_SUCCESS",
  USER_SIGNUP_FAIL: "user/USER_SIGNUP_FAIL",
  USER_SIGNOUT_START: "user/USER_SIGNOUT_START",
  USER_SIGNOUT_SUCCESS: "user/USER_SIGNOUT_SUCCESS",
  USER_SIGNOUT_FAIL: "user/USER_SIGNOUT_FAIL",
};
